CREATE TABLE IF NOT EXISTS crunchbase_organizations (
  company_name varchar,
  primary_role varchar,
  permalink varchar,
  domain varchar,
  homepage_url varchar,
  country_code char(3),
  state_code varchar,
  region varchar,
  city varchar,
  zipcode varchar,
  address varchar,
  status varchar,
  short_description varchar,
  category_list varchar,
  category_group_list varchar,
  funding_rounds smallint,
  funding_total_usd bigint,
  founded_on date,
  first_funding_on date,
  last_funding_on date,
  closed_on date,
  employee_count varchar,
  email varchar,
  phone varchar,
  facebook_url varchar,
  linkedin_url varchar,
  cb_url varchar,
  logo_url varchar,
  profile_image_url varchar,
  twitter_url varchar,
  alias varchar[],
  uuid uuid PRIMARY KEY,
  created_at timestamp,
  updated_at timestamp
);

\COPY crunchbase_organizations FROM 'organizations_transformed.csv' WITH CSV HEADER;
